### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brody2consult** [tlrobinson/streampunk.js#1]
This looks really awesome! Did you have any license in mind? Are you willing to consider public domain (like I saw for evil.css), MIT, or something else?

**Comment by tlrobinson** [comment]
Probably MIT or BSD.

**Comment by brody2consult** [comment]
Thanks! Do you know when you expect to decide?

**Comment by tlrobinson** [comment]
Now :) https://github.com/tlrobinson/sbp/commit/3a923fab723b456f587fe6100353b2e31b71efea
